import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
test.beforeEach(async({page,request})=>{
  await request.post('/api/session',{data:{tenant:'acme',persona:'support_manager'}});await request.post('/api/reset',{data:{confirm:'acme'}});await page.goto('/');await expect(page.getByRole('heading',{name:'Your deployment, at a glance.'})).toBeVisible();
});
test('automatic refund, ordered timeline, receipt and reload persistence',{tag:'@smoke'},async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'Start demo',exact:true}).click();await page.getByRole('button',{name:'Run workflow',exact:true}).click();await expect(page.locator('.message.assistant')).toContainText('$49.00 refund is confirmed');await expect(page.locator('.proposal')).toContainText('EXECUTION CONFIRMED');await page.reload();await expect(page.locator('.message.assistant')).toContainText('$49.00 refund is confirmed');await expect(page.locator('.timeline')).toContainText('write confirmed');expect(errors).toEqual([]);mkdirSync('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/support.png',fullPage:true});
});
test('large approval persists across refresh; manager approves exact action once',async({page})=>{
  await page.getByRole('button',{name:'Support workspace',exact:true}).click();await page.getByRole('button',{name:'Large refund',exact:true}).click();await page.getByRole('button',{name:'Run workflow',exact:true}).click();await expect(page.locator('.message.assistant')).toContainText('No action has executed');await page.getByRole('button',{name:'Approvals',exact:true}).click();await expect(page.getByText('$8,000.00',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Approve exact action'})).toBeVisible();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Approve exact action'}).click();await expect(page.getByText('Execution confirmed with receipt')).toBeVisible();await page.screenshot({path:'docs/screenshots/approval.png',fullPage:true});
});
test('external Jira ticket receives governed reply and resolves',async({page})=>{
  await page.getByRole('button',{name:'Existing support stack',exact:true}).click();const ticket=page.locator('.external-ticket').filter({hasText:'ACME-1042'});await ticket.getByRole('button',{name:'Process ticket'}).click();await expect(page.locator('.message.assistant')).toContainText('$49.00 refund is confirmed');await page.getByRole('button',{name:'Existing support stack',exact:true}).click();await expect(ticket).toContainText('Resolved');await ticket.getByText('Native fields, comments & status').click();await expect(ticket.locator('pre')).toContainText('jsdPublic');await expect(ticket.locator('pre')).toContainText('refund is confirmed');await page.screenshot({path:'docs/screenshots/integrations.png',fullPage:true});
});
test('discovery remediation changes real findings',async({page})=>{
  await page.getByLabel('Customer deployment').selectOption('messycorp');await page.getByRole('button',{name:'Customer discovery',exact:true}).click();await expect(page.getByText('unmapped-inv-49',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Apply verified account mapping'}).click();await expect(page.getByText('unmapped-inv-49',{exact:true})).toHaveCount(0);await expect(page.getByText('policy-conflict',{exact:true})).toBeVisible();await page.screenshot({path:'docs/screenshots/discovery.png',fullPage:true});
});
test('evaluation failure trace reruns in a fresh sandbox',async({page})=>{
  await page.getByRole('button',{name:'Evaluations',exact:true}).click();await page.getByRole('button',{name:'Run smoke',exact:true}).click();await expect(page.getByRole('heading',{name:'8 / 9 cases passed'})).toBeVisible();const row=page.getByRole('row').filter({hasText:'heldout-reversal'});await row.getByRole('button',{name:'Inspect',exact:true}).click();await expect(page.getByRole('heading',{name:'Execution record'})).toBeVisible();await page.getByRole('button',{name:'Rerun in isolated sandbox'}).click();await expect(page.getByRole('heading',{name:'Isolated simulation'})).toBeVisible();await expect(page.getByText('Original ledger preserved.',{exact:false})).toBeVisible();
});
test('mobile navigation remains named and fits the viewport',async({page})=>{
  await page.setViewportSize({width:390,height:844});await expect(page.getByRole('button',{name:'Support workspace',exact:true})).toBeVisible();await page.getByRole('button',{name:'Support workspace',exact:true}).click();await expect(page.getByLabel('Support request',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/mobile.png',fullPage:true});
});
test('overview screenshot and no console errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.reload();await expect(page.getByRole('heading',{name:'Your deployment, at a glance.'})).toBeVisible();await page.screenshot({path:'docs/screenshots/overview.png',fullPage:true});expect(errors).toEqual([]);});
