Foreground yes
User clamav
TCPSocket 3310
TCPAddr 0.0.0.0
PidFile /tmp/clamd.pid
LocalSocket /tmp/clamd.sock
DatabaseDirectory /var/lib/clamav
LogTime yes
MaxThreads 2
MaxQueue 8
StreamMaxLength 20M
MaxFileSize 20M
MaxScanSize 40M
MaxScanTime 20000
MaxRecursion 4
ReadTimeout 30
CommandReadTimeout 10
ScanArchive no
ScanPDF yes
ScanPE yes
ScanELF yes
AlertExceedsMax yes
