export const SHADOW_SCHEMA = `
CREATE TABLE IF NOT EXISTS shadow_candidates(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces ON DELETE CASCADE,name text NOT NULL,channel_id text NOT NULL REFERENCES channels ON DELETE CASCADE,draft_channel text NOT NULL,draft_revision integer NOT NULL,workflow_version integer NOT NULL,snapshot jsonb NOT NULL,fingerprint text NOT NULL,created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id),FOREIGN KEY(workspace_id,workflow_version) REFERENCES workflow_versions(workspace_id,version));
CREATE TABLE IF NOT EXISTS shadow_experiments(id text PRIMARY KEY,workspace_id text NOT NULL,candidate_id text NOT NULL,channel_id text NOT NULL REFERENCES channels ON DELETE CASCADE,status text NOT NULL DEFAULT 'active',config jsonb NOT NULL,sampling_key text NOT NULL,created_by text NOT NULL,request_key text NOT NULL,request_hash text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),ends_at timestamptz NOT NULL,reason text,UNIQUE(workspace_id,id),UNIQUE(workspace_id,request_key),FOREIGN KEY(workspace_id,candidate_id) REFERENCES shadow_candidates(workspace_id,id) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS shadow_active_channel ON shadow_experiments(workspace_id,channel_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS shadow_results(id text PRIMARY KEY,workspace_id text NOT NULL,experiment_id text NOT NULL,conversation_id text NOT NULL,source_run_id text NOT NULL REFERENCES runs ON DELETE CASCADE,source_revision integer NOT NULL,status text NOT NULL,history jsonb NOT NULL DEFAULT '[]',contact_snapshot jsonb,conversation_snapshot jsonb,fixtures jsonb NOT NULL DEFAULT '{}',baseline jsonb,output jsonb,rules jsonb,judge jsonb,reviews jsonb NOT NULL DEFAULT '[]',error text,started_at timestamptz,finished_at timestamptz,execution_ms integer,baseline_ms integer,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(experiment_id,conversation_id,source_revision),UNIQUE(workspace_id,id),FOREIGN KEY(workspace_id,experiment_id) REFERENCES shadow_experiments(workspace_id,id) ON DELETE CASCADE,FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS shadow_result_status ON shadow_results(workspace_id,experiment_id,status,created_at);
CREATE TABLE IF NOT EXISTS canary_rollouts(id text PRIMARY KEY,workspace_id text NOT NULL,experiment_id text NOT NULL,channel_id text NOT NULL REFERENCES channels ON DELETE CASCADE,candidate_id text NOT NULL,status text NOT NULL DEFAULT 'active',generation integer NOT NULL DEFAULT 1,percent integer NOT NULL,token_cap integer NOT NULL,max_failures integer NOT NULL,sampling_key text NOT NULL,created_by text NOT NULL,decision text NOT NULL,review_threshold integer NOT NULL,request_key text NOT NULL,request_hash text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),ends_at timestamptz NOT NULL,reason text,UNIQUE(workspace_id,id),UNIQUE(workspace_id,request_key),FOREIGN KEY(workspace_id,experiment_id) REFERENCES shadow_experiments(workspace_id,id),FOREIGN KEY(workspace_id,candidate_id) REFERENCES shadow_candidates(workspace_id,id));
CREATE UNIQUE INDEX IF NOT EXISTS canary_active_channel ON canary_rollouts(workspace_id,channel_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS canary_assignments(workspace_id text NOT NULL,conversation_id text NOT NULL,rollout_id text NOT NULL,generation integer NOT NULL,variant text NOT NULL CHECK(variant IN ('baseline','candidate')),workflow_version integer NOT NULL,revoked boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,conversation_id),FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE,FOREIGN KEY(workspace_id,rollout_id) REFERENCES canary_rollouts(workspace_id,id));
ALTER TABLE runs ADD COLUMN IF NOT EXISTS rollout_id text;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS rollout_generation integer;
ALTER TABLE usage ADD COLUMN IF NOT EXISTS experiment_id text;
ALTER TABLE usage ADD COLUMN IF NOT EXISTS rollout_id text;
CREATE INDEX IF NOT EXISTS usage_experiment ON usage(workspace_id,experiment_id);
CREATE INDEX IF NOT EXISTS usage_rollout ON usage(workspace_id,rollout_id);
`;
