export const SLA_SCHEMA = `
CREATE TABLE IF NOT EXISTS sla_policies(workspace_id text PRIMARY KEY REFERENCES workspaces ON DELETE CASCADE,revision integer NOT NULL,policy jsonb NOT NULL,enabled_since timestamptz,updated_by text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sla_policy_versions(workspace_id text NOT NULL REFERENCES workspaces ON DELETE CASCADE,revision integer NOT NULL,policy jsonb NOT NULL,created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,revision));
CREATE TABLE IF NOT EXISTS sla_observations(id bigserial PRIMARY KEY,workspace_id text NOT NULL,conversation_id text NOT NULL,origin text NOT NULL,kind text NOT NULL,at timestamptz NOT NULL,snapshot jsonb NOT NULL,processed_at timestamptz,UNIQUE(workspace_id,conversation_id,origin),FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS sla_observation_pending ON sla_observations(id) WHERE processed_at IS NULL;
CREATE TABLE IF NOT EXISTS sla_obligations(id text PRIMARY KEY,workspace_id text NOT NULL,conversation_id text NOT NULL,kind text NOT NULL CHECK(kind IN ('first','next','handoff')),state text NOT NULL CHECK(state IN ('running','paused','satisfied','breached','canceled')),origin text NOT NULL,policy_revision integer NOT NULL,policy jsonb NOT NULL,rule_id text NOT NULL,generation integer NOT NULL DEFAULT 1,started_at timestamptz NOT NULL,due_at timestamptz NOT NULL,warning_at timestamptz NOT NULL,escalate_at timestamptz NOT NULL,breached_at timestamptz,satisfied_at timestamptz,ended_at timestamptz,cause text NOT NULL,remaining_minutes real,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,conversation_id,kind,origin),FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE);
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS sla_checked_at timestamptz;
CREATE INDEX IF NOT EXISTS sla_due ON sla_obligations(workspace_id,due_at) WHERE ended_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS sla_one_response ON sla_obligations(workspace_id,conversation_id) WHERE ended_at IS NULL AND kind IN ('first','next');
CREATE UNIQUE INDEX IF NOT EXISTS sla_one_handoff ON sla_obligations(workspace_id,conversation_id) WHERE ended_at IS NULL AND kind='handoff';
CREATE TABLE IF NOT EXISTS sla_waits(id text PRIMARY KEY,workspace_id text NOT NULL,conversation_id text NOT NULL,source_message_id text NOT NULL,policy_revision integer NOT NULL,policy jsonb NOT NULL,conversation_revision integer NOT NULL,allowed boolean NOT NULL,actor_id text NOT NULL,created_at timestamptz NOT NULL, due_at timestamptz NOT NULL,sent_count integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'waiting',reason text,UNIQUE(workspace_id,conversation_id,source_message_id),FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS sla_one_wait ON sla_waits(workspace_id,conversation_id) WHERE status='waiting';
CREATE TABLE IF NOT EXISTS sla_notifications(id text PRIMARY KEY,workspace_id text NOT NULL,conversation_id text NOT NULL,obligation_id text NOT NULL REFERENCES sla_obligations ON DELETE CASCADE,generation integer NOT NULL,threshold text NOT NULL,recipient_id text NOT NULL,read_at timestamptz,email_status text NOT NULL DEFAULT 'disabled',email_attempted_at timestamptz,email_accepted_at timestamptz,error text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(obligation_id,generation,threshold,recipient_id),FOREIGN KEY(workspace_id,conversation_id) REFERENCES conversations(workspace_id,id) ON DELETE CASCADE);
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_role_check;
ALTER TABLE messages ADD CONSTRAINT messages_role_check CHECK(role IN ('customer','assistant','staff','note','system','reminder'));
ALTER TABLE messages ADD COLUMN IF NOT EXISTS sla_wait_id text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS sla_wait_generation integer;
`;
